### PR TITLE
Updating to V6 of the vbb transport rest API 

### LINKED ISSUE #15: Update API to V6
The V5 of the vbb transport rest API is marked as deprecated and currently not responding.

### PR DESCRIPTION
**Pull request by Gamdschi**
resolves #15

### CODE REVIEW

**Comment by Gamdschi** [comment]
You will need to update your IDs

**Comment by vas3k** [comment]
> You will need to update your IDs

Oh, did they change Stop ID's in the new API? Or which IDs you mean?

**Comment by Gamdschi** [comment]
Yes they've updated the stop IDs in the new API

**Comment by Gamdschi** [comment]
You can use the URL from the readme to find the updated Stop IDs

**Review by vas3k — APPROVED** [review]

**Comment by prepor** [comment]
> Yeah, I'm just worried about people who decide to update the widget and it will break their backward compatibility.

They disabled v5 API anyway, it stopped working, so there are no choices :)

**Pull request merged**
